site_name: Sistema de Información Climática NOAA
site_description: Documentación oficial para la plataforma de recepción, procesamiento y visualización de imágenes satelitales APT.

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Inicio: index.md
  - Arquitectura: arquitectura.md
  - Guía de Instalación: configuracion.md
  - Módulos:
      - Visión Artificial y Nowcasting: modulos/algoritmo_vision.md
      - SMN (Datos Oficiales): modulos/smn.md
      - OpenWeatherMap (API): modulos/owm.md
      - GOES-16 (Satelital): modulos/goes.md
      - Logs y Seguridad (PLG/CrowdSec): modulos/logs_seguridad.md
  - Visualización:
      - Arquitectura UI: frontend_dashboard.md
      - Guía de Monitoreo: visualizacion.md
  - Diseño Responsivo y Móvil: diseno_responsivo.md
  - Seguridad: seguridad.md
  - Bitácora de Desafíos: lecciones_aprendidas.md
  - Propuestas de Mejoras: futuras_mejoras.md
