# Definición de zonas de limitación
limit_req_zone $binary_remote_addr zone=mylimit:10m rate=3r/s;
limit_conn_zone $binary_remote_addr zone=addr:10m;

server {
    listen       8080;
    server_name  localhost;
    server_tokens off;

    # Aplicar limitaciones
    limit_req zone=mylimit burst=5 nodelay;
    limit_conn addr 10;

    # Mitigaciones contra Slowloris (Layer 7 DoS)
    client_body_timeout 10s;
    client_header_timeout 10s;
    keepalive_timeout 15s;
    send_timeout 10s;
    
    # Previene ataques de payload gigante (solo aceptas GET, no necesitas recibir cuerpos grandes)
    client_max_body_size 100K;

    # Cabeceras de Seguridad
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self';" always;

    # Restringir métodos HTTP: Solo lectura (GET y HEAD)
    if ($request_method !~ ^(GET|HEAD)$ ) {
        return 405;
    }

    location / {
        root   /var/www/html;
        index  index.html;
    }

    location /goes/ {
        alias /var/www/html/goes/;
        autoindex on;
        autoindex_format json;
        autoindex_exact_size off;
        autoindex_localtime on;
    }

    location /noaa/ {
        alias /var/www/html/noaa/;
        autoindex on;
        autoindex_format json;
        autoindex_exact_size off;
        autoindex_localtime on;
    }

    # Prevención contra Enumeración Volumétrica (Caché por defecto)
    location ~* \.(jpg|jpeg|png|json)$ {
        root /var/www/html;
        expires 10m;
        add_header Cache-Control "public, no-transform";
    }

    # Denegar acceso a archivos que empiezan con punto (ocultos)
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
